blank_issues_enabled: false
contact_links:
  - name: Bug Report on upstream llama.cpp
    url: https://github.com/ggml-org/llama.cpp/issues
    about: If your issue is not ROCm-specific, please report it to the upstream llama.cpp repository instead.
  - name: Bug Report on upstream ROCm
    url: https://github.com/ROCm/ROCm/issues
    about: If your issue is purely related to ROCm (not llama.cpp), please report it to the ROCm repository instead.
