blank_issues_enabled: true
contact_links:
  - name: Upstream llama.cpp
    url: https://github.com/ggml-org/llama.cpp/issues
    about: If your issue is not ROCm-specific, please report it to the upstream llama.cpp repository instead.
